# version format
version: 0.6.5.{build}
os: Windows Server 2012
environment:
  nodejs_version: "0.12"
  node_pre_gyp_accessKeyId:
    secure: 6Nx+sfUMeWB5K7VIEhY+QNxESzwqgUqteDEKThVsrzY=
  node_pre_gyp_secretAccessKey:
    secure: P9ANQwy4R1ER4phWUHRno80ikNq8PJ3dO6is9Gt1RCmdz/r4GdDOwc3mq/ykMelS
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - SET PATH=node_modules\.bin;%PATH%
  - node-pre-gyp --msvs_version=2013 package unpublish publish
test_script:
  - npm test
build: off
